<a href="https://colab.research.google.com/github/tsaunders7/DataScience/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>NumPy Beginner's Guide Third Edition</h1>
<h2>by Ivan Idris</h2>
<br>
<h3>Chapter 2. Beginning with NumPy Fundamentals</h3>

In [2]:
import numpy as np

In [ ]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if ``__array__`` returns a copy, if obj is a nested
        sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, e

<b>NumPy array object

In [ ]:
a = np.arange(5)
a.dtype

dtype('int64')

In [ ]:
a

array([0, 1, 2, 3, 4])

In [ ]:
a.shape

(5,)

<b>Time for action – creating a multidimensional array

In [ ]:
m = np.array([np.arange(4), np.arange(4)])
m

array([[0, 1, 2, 3],
       [0, 1, 2, 3]])

In [ ]:
m.shape

(2, 4)

In [ ]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [ ]:
a[0,0]

1

In [ ]:
a[0,1]

2

In [ ]:
a[1,1]

4

<b>NumPy numerical types

In [ ]:
np.finfo(np.float16)

finfo(resolution=0.001, min=-6.55040e+04, max=6.55040e+04, dtype=float16)

In [ ]:
np.float64(42)

42.0

In [ ]:
np.arange(7, dtype=np.uint16)

array([0, 1, 2, 3, 4, 5, 6], dtype=uint16)

In [ ]:
a

array([[1, 2],
       [3, 4]])

In [ ]:
a.shape

(2, 2)

In [ ]:
a.dtype.itemsize  #8 bytes

8

<b>Time for action – creating a record data type

In [ ]:
t = np.dtype([('name', np.str_, 40), ('numitems', np.int32), ('price', np.float32)])
t

dtype([('name', '<U40'), ('numitems', '<i4'), ('price', '<f4')])

In [ ]:
t['name']

dtype('<U40')

In [ ]:
itemz = np.array([('Meaning of life DVD', 42, 3.14), ('Butter', 13, 2.72)], t)
itemz[1]

('Butter', 13, 2.72)

<b>One-dimensional slicing and indexing

In [ ]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
a[3:7]

array([3, 4, 5, 6])

In [ ]:
a[:7:2]

array([0, 2, 4, 6])

In [ ]:
a[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1, 0])

<b>Time for action – slicing and indexing multidimensional arrays

In [ ]:
np.arange(24)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
b = np.arange(24).reshape(2,3,4)
b.shape

(2, 3, 4)

In [ ]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

NOTE: Array operations using b

In [ ]:
b[0,0,2]

2

In [ ]:
b[1,2,2]

22

In [ ]:
b[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b[0,1]

array([4, 5, 6, 7])

In [ ]:
b[0, :, :]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b[0, ...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b[0,1,::2]    #::2  select every second element

array([4, 6])

In [ ]:
b[...,1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [ ]:
b[:,1]    #select all row 1 items from both arrays

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [ ]:
b[0,:,-1]  #select last column of first array

array([ 3,  7, 11])

In [ ]:
b[0,::-1, -1]   #reverse order of last column of first array

array([11,  7,  3])

In [ ]:
b[:,:,1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [ ]:
b[0,::2,-1]

array([ 3, 11])

In [ ]:
b[::-1]

array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

<b>Time for action – manipulating array shapes

In [ ]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
b.flatten()  #same as ravel but new memory location allocated

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
b.shape = (6,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
b.transpose()

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [ ]:
b.resize((2,12))
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

<b>Time for action – stacking arrays

In [ ]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
b = 2 * a
b

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [ ]:
np.hstack((a, b))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [ ]:
np.concatenate((a, b), axis=1)

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [ ]:
np.vstack((a, b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [ ]:
np.concatenate((a, b), axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [ ]:
np.dstack((a, b))   #depth stacking

array([[[ 0,  0],
        [ 1,  2],
        [ 2,  4]],

       [[ 3,  6],
        [ 4,  8],
        [ 5, 10]],

       [[ 6, 12],
        [ 7, 14],
        [ 8, 16]]])

In [ ]:
oned = np.arange(2)
oned

array([0, 1])

In [ ]:
twice_oned = 2 * oned
twice_oned

array([0, 2])

In [ ]:
np.column_stack((oned, twice_oned))

array([[0, 0],
       [1, 2]])

In [ ]:
np.column_stack((a, b))   #similar to hstack

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [ ]:
np.column_stack((a, b)) == np.hstack((a, b))

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [ ]:
np.row_stack((oned, twice_oned))  #similar to vstack

array([[0, 1],
       [0, 2]])

In [ ]:
np.row_stack((a, b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [ ]:
np.row_stack((a,b)) == np.vstack((a, b))

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

<b>Time for action – splitting arrays

In [ ]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.hsplit(a, 3)

[array([[0],
        [3],
        [6]]),
 array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]])]

In [ ]:
np.split(a, 3, axis=1)

[array([[0],
        [3],
        [6]]),
 array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]])]

In [ ]:
np.vsplit(a, 3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [ ]:
np.split(a, 3, axis=0)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [ ]:
c = np.arange(27).reshape(3, 3, 3)
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
np.dsplit(c, 3)

[array([[[ 0],
         [ 3],
         [ 6]],
 
        [[ 9],
         [12],
         [15]],
 
        [[18],
         [21],
         [24]]]),
 array([[[ 1],
         [ 4],
         [ 7]],
 
        [[10],
         [13],
         [16]],
 
        [[19],
         [22],
         [25]]]),
 array([[[ 2],
         [ 5],
         [ 8]],
 
        [[11],
         [14],
         [17]],
 
        [[20],
         [23],
         [26]]])]

In [3]:
b = np.arange(24).reshape(2,3,4)
b

In [4]:
b.resize((2,12))
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [5]:
b.ndim

2

In [6]:
b.size

24

In [7]:
b.itemsize

8

In [8]:
b.nbytes

192

In [9]:
b.resize(6,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [10]:
b.T

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [11]:
b.ndim

2

In [22]:
b = np.array([1.j + 1, 2.j + 3])
b

array([1.+1.j, 3.+2.j])

In [15]:
b.real

array([1., 3.])

In [16]:
b.imag

array([1., 2.])

In [17]:
b.dtype

dtype('complex128')

In [18]:
b.dtype.str

'<c16'

In [23]:
b = np.arange(4).reshape(2,2)
b

array([[0, 1],
       [2, 3]])

In [25]:
f = b.flat
f

In [27]:
for item in f: print(item)

1
2
3


In [28]:
b.flat[2]

2

In [29]:
b.flat[[1,3]]

array([1, 3])

In [30]:
b.flat = 7
b

array([[7, 7],
       [7, 7]])

In [31]:
b.flat[[1,3]] = 1
b

array([[7, 1],
       [7, 1]])

<b>Time for action – converting arrays

In [33]:
b = np.array([1.j + 1, 2.j + 3])
b

array([1.+1.j, 3.+2.j])

In [34]:
b.tolist()

[(1+1j), (3+2j)]

In [35]:
b.astype(int)

<ipython-input-35-3edadc125634>:1: ComplexWarning: Casting complex values to real discards the imaginary part
  b.astype(int)


array([1, 3])

In [36]:
b.astype('complex')

array([1.+1.j, 3.+2.j])